### ISSUE TITLE
Secondary Sort issue

### ISSUE THREAD

**Issue by Mottie** [Sjeiti/TinySort#116]
The secondary sort method is not working as expected. Maybe I'm not doing something correctly?

In [this demo](https://jsfiddle.net/Mottie/st0eotwo/1/), I would like the numbers to be sorted *after* the letters are sorted

```html
<ul>
  <li><span class="test">1</span></li>
  <li><span class="test" data-mod="c">3</span>c</li>
  <li><span class="test">5</span></li>
  <li><span class="test">7</span></li>
  <li><span class="test" data-mod="b">0</span>b</li>
  <li><span class="test">4</span></li>
  <li><span class="test" data-mod="a">9</span>a</li>
</ul>
```

```js
tinysort('li', {
  selector: '.test[data-mod]',
  attr: 'data-mod',
  place : 'start',
  direction: 'asc'
},{
  selector: '.test',
  place: 'start',
  direction: 'desc'
});
```

I am expecting the resulting sort to be:

> 9a
0b
3c
1
4
5
7

Also, when the primary sort selector doesn't have `[data-mod]` included, it appears to completely ignore the primary sort. I am also expecting that an undefined or empty `data-mod` attribute would make the primary sort leave those elements at the end, but instead it seems to default to the secondary sort.

**Comment by Sjeiti** [comment]
Ah that's not right, I'll have a look (but it might take some time).

**Comment by Sjeiti** [comment]
It's fixed but not merged to master yet.

Nice bug though; on the one hand your initial call was wrong (but that's understandable since the right call wouldn't work either). Multiple sort criteria (ie `tinysort('a',{},{},{},{})`) will only work with the selector of the first since the next criterium will only be used if the first encounters equal values.

The real issue here was this: `null>'c' // false` and `'c'>null // false`. So now when an attribute doesn't exist it will just use a very high char.

With the fix in this branch your initial call can be simplified to this:

```javascript
    tinysort('li', {
      selector: 'span'
      ,data: 'mod'
    },{});
```

Maybe I'll merge to master and tag tonight, maybe not. I'll have to check. I'll leave the issue open until then.

**Comment by Mottie** [comment]
Great! Thanks!
