### ISSUE TITLE
sorting vertically in 2 columns

### ISSUE THREAD

**Issue by starchild** [Sjeiti/TinySort#129]
Hi,

I have an UL which is being shown in two cols using CSS.  How can I use this plugin to sort my data so the sorting is done vertically, in both columns and not horizontally please?

eg 
A     L
v      v
K     Z

and not 

A > K
L > Z

**Comment by Sjeiti** [comment]
Check [this example](http://tinysort.sjeiti.com/#sorting-tables) or [this example] (http://tinysort.sjeiti.com/#multiple-sort-criteria)

**Comment by starchild** [comment]
Hi,

Thank you for your reply, but I don't see how either of these solve the solution of sorting a single UL into two vertically sorted columns?

**Comment by Sjeiti** [comment]
Alright,

If you setup a jsfiddle with your desired DOM I'll show you ...

**Comment by starchild** [comment]
Hi mate, ok here you go: https://jsfiddle.net/starchild/8hv22erx/5/

**Comment by Sjeiti** [comment]
Ah well no, this will not work because you have your CSS making the list elements flow into two colums by floating it left. But when reading the DOM it is one list. You will have to write your own custom sort if you keep your styling like this. It would work if you change your CSS to a flexbox layout to create a more natural column layout.

https://jsfiddle.net/Sjeiti/8hv22erx/6/

But this would mean having to give your list some height to force the overflow to the second column.
