### ISSUE TITLE
Tinysort does not sort if table is inside a dialog box

### ISSUE THREAD

**Issue by umbundu** [Sjeiti/TinySort#133]
I added a table to my document body and sorting works fine. If I add a similar table to a dialog that is open after the page is loaded; sorting does nothing even though the column headers are updated with asc/desc.

thanks,
Everardo

**Comment by Sjeiti** [comment]
I'd like to help but you offer little practical information on how to reproduce this. Please provide a [jsfiddle](https://jsfiddle.net/) with a proper example.

**Comment by umbundu** [comment]
I am sorry, here you go: https://jsfiddle.net/huambo/e8aerz3g/16/
I had to add all the setup code again in the section that opens the dialog or the sorting won't work. Is there a shortcut to basic sorting?
thanks.
Everardo

**Comment by Sjeiti** [comment]
Hey Everardo,

I checked your fiddle. I see that you are using Tinysort v1.2.18. You might want to consider updating to the latest version, although that doesn't solve your problem.

The problem you're having is not with Tinysort but with basic Javascript events, namely jQueries event implementation.
The example you copied to use is an example in the sense that it just should how you *could* use Tinysort. It is not optimised in any way.

The problem here is that events are added to the Elements themselves, while new elements are being added on the fly:

    $('table.whatever').on('click', function ...

What you want is for events to be added to body. Something like:

    $(document.body).on('click', 'table.whatever', function ...

So rewrite those, and you should be good to go.
