### ISSUE TITLE
Code Scan Issue - Insecure Randomness in tinysort.js

### ISSUE THREAD

**Issue by monika020627** [Sjeiti/TinySort#134]
Hi ,

We are using the tinysort plugin version 2.3.6 in our website. Our security team ran the code scan and found the “HIGH” security risk in the tinysort.js at line no. 280.

`sortReturnNumber = criterium.sortFunction(a,b);
        } else if (criterium.order=='rand') { // random sort
          sortReturnNumber = Math.random()<0.5?1:-1;
`
Attaching the detailed information of the issue.
Please let us know if you have a solution for this available in some patch or some newer version.

Thanks,
M
[TinySort-Insecure Randomness.docx](https://github.com/Sjeiti/TinySort/files/1156502/TinySort-Insecure.Randomness.docx)

**Comment by Sjeiti** [comment]
Hi Monika,

Has your security team read what this code does?
It does a random sort, using Math.random().
Explain to me how exactly this is a “HIGH” security risk and I might take this claim serious but for now I'm closing this issue as invalid.

You could always fork and patch the code yourself if you feel uncomfortable using it in its current state.

ps: I've read the docx and it doesn't explain a thing. In the future you might want to refrain from attaching files like that. It looks very dubious especially since your account is fresh. I had to go through virus-scan-proxy-open loops to read a file that you could have just copy pasted as text.
