### ISSUE TITLE
Sort by sub-selection seems to ignore sort order

### ISSUE THREAD

**Issue by wzol** [Sjeiti/TinySort#147]
Thank for the previous update 👍 

Like if I do a `tinysort('ul#xsub>li','span:nth-child(2)',{order:'desc'});` on the demo page it still orders the items in ascending order.

**Comment by Sjeiti** [comment]
No, it's intented behavior due to a confusing overload exception (which I completely forgot about).
Normal signature is this:

`tinysort({NodeList},{object})`

For secondary sorting the signature is repeated:

`tinysort({NodeList},{object},{NodeList},{object})`

Any parameters of the same type can be left out if it's the same as the previous so mostly you'll use something like:

`tinysort({NodeList},{object},{object},{object}...)`

With the one exception you encountered: if you have two parameters and your second parameter is an object with just a single property 'element' you can simply pass the value of said property.

So in your case it sorts the list elements to the text value of the second span, and if the are the same it will do a secondary sort to the text value of the entire list element in descending order.

What you probably meant was:

tinysort('ul#xsub>li',{order:'desc',element:'span:nth-child(2)'});

**Comment by Sjeiti** [comment]
This 'feature' is maybe better refactored away as it is really inconsistent. It probably stems from before the ability to do secondary sorting (so it wasn't always this confusing).

I'll have another good look at the code and the signature in terms of clarity since more people seem to strugle with it.
