### ISSUE TITLE
auto-played HTML5 video stops

### ISSUE THREAD

**Issue by jsrobinson** [Sjeiti/TinySort#92]
I have several HTML5 video containers that autoplay, I want to alphabetize them in the DOM (not server-side), so I use tinysort, but when tinysort executes, all of the HTML5 video stops.

**Comment by Sjeiti** [comment]
That's expected behavior since the DOM elements are detached and then attached again.
A tricky problem though. What you should do is store the following: for each video check if it is indeed playing and store the video.currentTime. Then sort and set the video.currentTime to the stored values. 
I haven't tested this but I can imagine the playback stuttering if you use this solution. What you could also take a look at is (css flex)[https://developer.mozilla.org/en-US/docs/Web/CSS/flex] since that does allow you to change the element order without changing the DOM order. But that would mean ditching Tinysort and writing your own sort function or only using Tinysort as a sort of 'shadow DOM' to adjust your video CSS properties to.

**Comment by Sjeiti** [comment]
Come to think of it, css flex order might me a really cool enhancement. Must check the performance for that...

**Comment by Sjeiti** [comment]
Well it's interesting enough to implement, on a local test I'm seeing a speed increase of about 180% across all browsers (for a ul>li*1000). JSPerf is showing something different though: https://jsperf.com/tinysort-flex-order

**Comment by jsrobinson** [comment]
so I followed your first suggestion (roughly) and just looped through all video and .play()'d them. It worked well. I am evaluating css flex as I had never seen it before. Thank you for the follow up!
